### ISSUE TITLE
webpack 4: DeprecationWarning

### ISSUE THREAD

**Issue by apepper** [robertbg/write-json-webpack-plugin#3]
When running `write-json-webpack-plugin` together with webpack 4, you'll get the following deprecation warning:

```
(node:13219) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

Here are some links, that might help while fixing the issues:

* https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202
* https://blog.johnnyreilly.com/2018/01/finding-webpack-4-use-map.html

**Comment by davidfou** [comment]
Thanks for your issue. It also highlights the lack of `peerDependencies` declaration on `package.json`.
